reference: ./clones/chr21.fa
config_files:
                0: 'configs/clone_configs/svs_0.yaml'
                1: 'configs/clone_configs/svs_1.yaml'
                2: 'configs/clone_configs/svs_2.yaml'
                3: 'configs/clone_configs/svs_3.yaml'
                4: 'configs/clone_configs/svs_4.yaml'


clones:
    A:
     - 0
    B:
      - 0
      - 1
    C:
      - 0
      - 1
      - 2
    D:
      - 0
      - 1
      - 3
    E: [0, 4]

purity:
  A: 30
  B: 20
  C: 20
  D: 20
  E: 10

coverage: 30