# YAML CONFIG FILE
reference: 'chr21_ref/chr21.fa'
max_tries: 200
random_seed: 42
variant_sets:
    - type: "DEL"
      number: 5
      length_ranges: [[50, 1000]]
    - type: "DUP"
      number: 5
      length_ranges: [[50, 1000]]
    - type: "INV"
      number: 5
      length_ranges: [[50, 1000]]
    - type: "dDUP"
      number: 5
      length_ranges:
        - [50, 1000]
      dispersion_ranges:
        - [100, 5000]