# YAML CONFIG FILE
sim_settings:
    reference: 'chr21_ref/chr21.fa'
    max_tries: 200
    prioritize_top: True
SVs:
    - type: "DEL"
      number: 5
      min_length: 50
      max_length: 1000
    - type: "DUP"
      number: 5
      min_length: 50
      max_length: 1000
    - type: "INV"
      number: 5
      min_length: 50
      max_length: 1000
    - type: "dDUP"
      number: 5
      min_length:
        - 50
        - 100
      max_length:
        - 1000
        - 5000
