import sys

def get_header():
    return ("version 1.0\n"
              "# -------- AUTOGENERATED FILE --------\n"
              "import \"insilicosv_tree_level_workflow.wdl\" as insilico_tree\n"
              "import \"insilicosv_read_mix.wdl\" as read_mix\n"
              "workflow GenomeMix {\n"
              "input { \n"
              "\tString outDir\n"
              "\tString reference\n"
              "\tArray[File] configs\n"
              "\tArray[Array[Int]] genomes\n"
              "\tArray[Float]? prevalence\n"
              "\tInt? totalCoverage\n"
              "\tBoolean? short\n"
              "\tBoolean? hifi\n"
              "\tBoolean? ont\n"
              "\tInt? threads\n"
              "}\n"
            )

def get_tree_level_block(level):
    return ("call insilico_tree.SimulateLineageTreeLevel as TreeLevel%d {\n"
            "\tinput:\n"
            "\t\toutDir = outDir,\n"
            "\t\tgenomes = genomes,\n"
            "\t\tinsilicoConfigs = configs,\n"
            "\t\ttreeLevel = %d,\n"
            "\t\toriginalRef = reference"
            "%s"
            "}\n" % (level, level, ",\n\t\tpreviousRef = TreeLevel%d.ref\n" % (level - 1) if level > 0 else "\n")
    )

def optional_readmix_block():
    return ("if (defined(totalCoverage)) {\n"
            "\tcall read_mix.SimulateReadMix as readMix {\n"
            "\t\tinput:\n"
            "\t\t\toutDir = outDir,\n"
            "\t\t\toriginalRef = reference,\n"
            "\t\t\tgenomes = genomes,\n"
            "\t\t\ttreeRefs = TreeLevel%d.ref,\n" 
            "\t\t\tprevalence = select_first([prevalence]),\n"
            "\t\t\ttotalCoverage = select_first([totalCoverage]),\n"
            "\t\t\tshort = short,\n"
            "\t\t\thifi = hifi,\n"
            "\t\t\tont = ont,\n"
            "\t\t\tthreads = threads\n"
            "\t}\n}\n" % (max_tree_depth-1)
            )

def get_output_block():
    block = ""
    for i in range(max_tree_depth):
        block += "\tArray[File] ref%d = TreeLevel%d.ref\n\tArray[File] vcf%d = TreeLevel%d.vcf\n" % (i, i, i, i)
    block += ("\tFile? srBAM = readMix.srBAM\n"
              "\tFile? srBAI = readMix.srBAI\n"
              "\tFile? hifiBAM = readMix.hifiBAM\n"
              "\tFile? hifiBAI = readMix.hifiBAI\n"
              "\tFile? ontBAM = readMix.ontBAM\n"
              "\tFile? ontBAI = readMix.ontBAI\n"
              )
    return "output {\n%s}\n}\n" % block

max_tree_depth = int(sys.argv[1])
workflow_name = "insilicosv_lineage_workflow_%d.wdl" % max_tree_depth
with open(workflow_name, "w") as f:
    f.write(get_header() +
            "\n".join(get_tree_level_block(i) for i in range(max_tree_depth)) +
            "\n" + optional_readmix_block() +
            "\n" + get_output_block()
            )