# YAML CONFIG FILE
heterozygous_only: True
variant_sets:
  - type: "DEL"
    number: 5
    length_ranges: [ [ 5000, 10000 ] ]
  - type: "DUP"
    number: 5
    length_ranges: [ [ 5000, 10000 ] ]
  - type: "SNP"
    number: 50
    enable_overlap_sv: True